### Cargar paquetes, definir setup y tema de gráficas ----
source("02_codigo/00_paquetes_setup_tema.R")

### Importar datos ---- 
bd_indice <- 
  read_excel("01_datos/02. Aplicación del Índice de Fortaleza de Cuota en la Legislación Federal y Estatal en México (1990-2016) 29.11.2016.xlsx",
             range = "a1:k263") %>% 
  clean_names() %>% 
  rename(ifreg = ifc)

### Limpiar y transformar -----
bd_indice_edos <- 
  bd_indice %>% 
  # Eliminar observaciones de normas federales
  filter(!str_detect(entidad, "Federal ")) %>% 
  # Generar variable para identificar número de norma
  mutate(num_norma = case_when(str_detect(entidad, " IX") ~ 9,
                               str_detect(entidad, " IV") ~ 4,
                               str_detect(entidad, " III") ~ 3,
                               str_detect(entidad, " II") ~ 2,
                               str_detect(entidad, " I") ~ 1,
                               str_detect(entidad, " VIII") ~ 8,
                               str_detect(entidad, " VII") ~ 7,
                               str_detect(entidad, " VI") ~ 6,
                               str_detect(entidad, " V") ~ 5,
                               str_detect(entidad, " XIV") ~ 14,
                               str_detect(entidad, " XIII") ~ 13,
                               str_detect(entidad, " XII") ~ 12,
                               str_detect(entidad, " XI") ~ 11,
                               str_detect(entidad, " X") ~ 10),
         estado = case_when(str_detect(entidad, "Aguas") ~ "Aguascalientes",
                            # entidad == "Baja California" ~ "Baja California",
                            str_detect(entidad, " Sur") ~ "Baja California Sur",
                            str_detect(entidad, "Baja California I") ~ "Baja California",
                            str_detect(entidad, "Campeche") ~ "Campeche",
                            str_detect(entidad, "Chia") ~ "Chiapas",
                            str_detect(entidad, "Chih") ~ "Chihuahua",
                            str_detect(entidad, "Ciudad de ") ~ "Ciudad de México",
                            str_detect(entidad, "Coah") ~ "Coahuila",
                            str_detect(entidad, "Col") ~ "Colima",
                            str_detect(entidad, "Durango") ~ "Durango",
                            str_detect(entidad, "Estado de ") ~ "Estado de México",
                            str_detect(entidad, "Guana") ~ "Guanajuato",
                            str_detect(entidad, "Guerr") ~ "Guerrero",
                            str_detect(entidad, "Hid") ~ "Hidalgo",
                            str_detect(entidad, "Jal") ~ "Jalisco",
                            str_detect(entidad, "Mich") ~ "Michoacán",
                            str_detect(entidad, "Mor") ~ "Morelos",
                            str_detect(entidad, "Nay") ~ "Nayarit",
                            str_detect(entidad, "Nuevo") ~ "Nuevo León",
                            str_detect(entidad, "Oax") ~ "Oaxaca",
                            str_detect(entidad, "Pue") ~ "Puebla",
                            str_detect(entidad, "Quer") ~ "Querétaro",
                            str_detect(entidad, "Quint") ~ "Quintana Roo",
                            str_detect(entidad, "San") ~ "San Luis Potosí",
                            str_detect(entidad, "Sin") ~ "Sinaloa",
                            str_detect(entidad, "Son") ~ "Sonora",
                            str_detect(entidad, "Tab") ~ "Tabasco",
                            str_detect(entidad, "Tam") ~ "Tamaulipas",
                            str_detect(entidad, "Tlax") ~ "Tlaxcala",
                            str_detect(entidad, "Ver") ~ "Veracruz",
                            str_detect(entidad, "Yuc") ~ "Yucatán",
                            str_detect(entidad, "Zac") ~ "Zacatecas"))  %>% 
  # Reordenar columnas
  select(estado, num_norma, entidad, ley, everything()) %>% 
  # Renombrar columnas
  rename(año_publicacion = ano_de_publicacion_de_la_ley)


### Generar variable num_elecciones y año_eleccion ----

# Originalmente la base de datos del índice no contiene una columna que indique en qué elección o elecciones estuvo vigente y se aplicó cada una de las normas. Esta columna es necesaria para después poder unir los datos del % de diputadas en cada legislatura y estado con los datos del índice. 

# En esta sección construimos dicha variable, llamada año_eleccion. Para hacerlo, antes construimos la variable num_elecciones. Esta última indica en cuántas elecciones estuvo vigente la normal y nos permitirá repetir la observación correspondiente a una norma tantas veces como elecciones haya estado vigente. Posteriormente construimos año_eleccion e identificamos en qué elecciones en particular estuvo vigente cada norma

### Construcción de num_elecciones ----

# Al construir esta variable consideramos que una norma estuvo vigente en los años *posteriores* a que fue emitida, hasta que una nueva norma fue emitida (en su caso). Esto implica:

# - Que si una norma fue emitida en 2009 y hubo elecciones ese año, no consideramos que la norma estuvo vigente para esa elección, sino para las subsecuentes. Esta decisión se basa en que en materia electoral la regla suele ser que no se pueden hacer cambios a las normas una vez iniciado el proceso, y esto suele ocurrir el año previo al de la elección.

# - Que si se emitieron dos normas en 2007 y 2008, y las elecciones fueron en 2006 y 2009, la norma que tomamos en cuenta para 2009 es la de 2008 y la de 2007 no será incluida en el análisis. 

bd_indice_edos <- 
  bd_indice_edos %>% 
  mutate(num_elecciones = case_when(estado == "Aguascalientes" & año_publicacion == 2003 ~ 2,
                                    estado == "Aguascalientes" & año_publicacion == 2009 ~ 1,
                                    estado == "Aguascalientes" & año_publicacion == 2012 ~ 1,
                                    estado == "Aguascalientes" & año_publicacion == 2015 ~ 2,
                                    estado == "Baja California" & año_publicacion == 2008 ~ 2,
                                    estado == "Baja California" & año_publicacion == 2015 ~ 2,
                                    estado == "Baja California Sur" & año_publicacion == 2003 ~ 1,
                                    estado == "Baja California Sur" & año_publicacion == 2007 ~ 2,
                                    estado == "Baja California Sur" & año_publicacion == 2014 ~ 2,
                                    estado == "Campeche" & año_publicacion == 2002 ~ 1,
                                    estado == "Campeche" & año_publicacion == 2005 ~ 1,
                                    estado == "Campeche" & año_publicacion == 2008 ~ 1,
                                    estado == "Campeche" & año_publicacion == 2011 ~ 1,
                                    estado == "Campeche" & año_publicacion == 2014 ~ 2,
                                    estado == "Chiapas" & año_publicacion == 2005 ~ 1,
                                    estado == "Chiapas" & año_publicacion == 2008 ~ 1,
                                    estado == "Chiapas" & año_publicacion == 2010 ~ 0, 
                                    estado == "Chiapas" & año_publicacion == 2011 ~ 1,
                                    estado == "Chiapas" & año_publicacion == 2013 ~ 0, 
                                    estado == "Chiapas" & año_publicacion == 2014 ~ 2,
                                    estado == "Chihuahua" & año_publicacion == 1997 ~ 4,
                                    estado == "Chihuahua" & año_publicacion == 2009 ~ 2,
                                    estado == "Chihuahua" & año_publicacion == 2014 ~ 0,
                                    estado == "Chihuahua" & año_publicacion == 2015 ~ 2,
                                    estado == "Ciudad de México" & año_publicacion == 1999 ~ 1,
                                    estado == "Ciudad de México" & año_publicacion == 2001 ~ 1,
                                    estado == "Ciudad de México" & año_publicacion == 2003 ~ 0,
                                    estado == "Ciudad de México" & año_publicacion == 2005 ~ 1,
                                    estado == "Ciudad de México" & año_publicacion == 2008 ~ 1,
                                    estado == "Ciudad de México" & año_publicacion == 2011 ~ 1,
                                    estado == "Ciudad de México" & año_publicacion == 2014 ~ 2,
                                    estado == "Coahuila" & año_publicacion == 2001 ~ 3,
                                    estado == "Coahuila" & año_publicacion == 2009 ~ 0,
                                    estado == "Coahuila" & año_publicacion == 2010 ~ 2,
                                    estado == "Coahuila" & año_publicacion == 2016 ~ 1,
                                    estado == "Colima" & año_publicacion == 1999 ~ 1,
                                    estado == "Colima" & año_publicacion == 2002 ~ 1,
                                    estado == "Colima" & año_publicacion == 2005 ~ 3,
                                    estado == "Colima" & año_publicacion == 2014 ~ 2,
                                    estado == "Durango" & año_publicacion == 2000 ~ 3,
                                    estado == "Durango" & año_publicacion == 2008 ~ 1,
                                    estado == "Durango" & año_publicacion == 2012 ~ 1,
                                    estado == "Durango" & año_publicacion == 2015 ~ 2,
                                    estado == "Estado de México" & año_publicacion == 1999 ~ 3,
                                    estado == "Estado de México" & año_publicacion == 2008 ~ 2,
                                    estado == "Estado de México" & año_publicacion == 2013 ~ 0,
                                    estado == "Estado de México" & año_publicacion == 2014 ~ 2,
                                    estado == "Guanajuato" & año_publicacion == 1994 ~ 2,
                                    estado == "Guanajuato" & año_publicacion == 2002 ~ 4,
                                    estado == "Guanajuato" & año_publicacion == 2014 ~ 2,
                                    estado == "Guerrero" & año_publicacion == 1998 ~ 2,
                                    estado == "Guerrero" & año_publicacion == 2004 ~ 2,
                                    estado == "Guerrero" & año_publicacion == 2008 ~ 1,
                                    estado == "Guerrero" & año_publicacion == 2014 ~ 2,
                                    estado == "Hidalgo" & año_publicacion == 2007 ~ 1,
                                    estado == "Hidalgo" & año_publicacion == 2009 ~ 2,
                                    estado == "Hidalgo" & año_publicacion == 2014 ~ 2, 
                                    estado == "Jalisco" & año_publicacion == 2002 ~ 1,
                                    estado == "Jalisco" & año_publicacion == 2005 ~ 1,
                                    estado == "Jalisco" & año_publicacion == 2008 ~ 2,
                                    estado == "Jalisco" & año_publicacion == 2014 ~ 2,
                                    estado == "Michoacán" & año_publicacion == 2001 ~ 1,
                                    estado == "Michoacán" & año_publicacion == 2005 ~ 0,
                                    estado == "Michoacán" & año_publicacion == 2007 ~ 2,
                                    estado == "Michoacán" & año_publicacion == 2014 ~ 2,
                                    estado == "Morelos" & año_publicacion == 2008 ~ 2,
                                    estado == "Morelos" & año_publicacion == 2013 ~ 0,
                                    estado == "Morelos" & año_publicacion == 2014 ~ 2,
                                    estado == "Nayarit" & año_publicacion == 2013 ~ 2,
                                    estado == "Nuevo León" & año_publicacion == 2008 ~ 2,
                                    estado == "Nuevo León" & año_publicacion == 2014 ~ 2,
                                    estado == "Oaxaca" & año_publicacion == 1997 ~ 3,
                                    estado == "Oaxaca" & año_publicacion == 2008 ~ 1,
                                    estado == "Oaxaca" & año_publicacion == 2012 ~ 3,
                                    estado == "Puebla" & año_publicacion == 2000 ~ 4,
                                    estado == "Puebla" & año_publicacion == 2012 ~ 1,
                                    estado == "Puebla" & año_publicacion == 2013 ~ 1,
                                    estado == "Puebla" & año_publicacion == 2014 ~ 0,
                                    estado == "Puebla" & año_publicacion == 2015 ~ 0,
                                    estado == "Puebla" & año_publicacion == 2016 ~ 1,
                                    estado == "Querétaro" & año_publicacion == 2002 ~ 1,
                                    estado == "Querétaro" & año_publicacion == 2005 ~ 1,
                                    estado == "Querétaro" & año_publicacion == 2008 ~ 2,
                                    estado == "Querétaro" & año_publicacion == 2014 ~ 2,
                                    estado == "Quintana Roo" & año_publicacion == 2004 ~ 1,
                                    estado == "Quintana Roo" & año_publicacion == 2007 ~ 1,
                                    estado == "Quintana Roo" & año_publicacion == 2010 ~ 1,
                                    estado == "Quintana Roo" & año_publicacion == 2011 ~ 0,
                                    estado == "Quintana Roo" & año_publicacion == 2012 ~ 1,
                                    estado == "Quintana Roo" & año_publicacion == 2015 ~ 2,
                                    estado == "San Luis Potosí" & año_publicacion == 1999 ~ 1,
                                    estado == "San Luis Potosí" & año_publicacion == 2002 ~ 2,
                                    estado == "San Luis Potosí" & año_publicacion == 2008 ~ 2,
                                    estado == "San Luis Potosí" & año_publicacion == 2014 ~ 2,
                                    estado == "Sinaloa" & año_publicacion == 1998 ~ 2,
                                    estado == "Sinaloa" & año_publicacion == 2006 ~ 2,
                                    estado == "Sinaloa" & año_publicacion == 2012 ~ 1,
                                    estado == "Sinaloa" & año_publicacion == 2015 ~ 2,
                                    estado == "Sonora" & año_publicacion == 1996 ~ 3,
                                    estado == "Sonora" & año_publicacion == 2005 ~ 3,
                                    estado == "Sonora" & año_publicacion == 2013 ~ 0,
                                    estado == "Sonora" & año_publicacion == 2014 ~ 2,
                                    estado == "Tabasco" & año_publicacion == 2002 ~ 2,
                                    estado == "Tabasco" & año_publicacion == 2008 ~ 1,
                                    estado == "Tabasco" & año_publicacion == 2011 ~ 1,
                                    estado == "Tabasco" & año_publicacion == 2014 ~ 2,
                                    estado == "Tamaulipas" & año_publicacion == 2003 ~ 1,
                                    estado == "Tamaulipas" & año_publicacion == 2006 ~ 1,
                                    estado == "Tamaulipas" & año_publicacion == 2008 ~ 2,
                                    estado == "Tamaulipas" & año_publicacion == 2015 ~ 1,
                                    estado == "Tlaxcala" & año_publicacion == 2004 ~ 2,
                                    estado == "Tlaxcala" & año_publicacion == 2012 ~ 1,
                                    estado == "Tlaxcala" & año_publicacion == 2015 ~ 2,
                                    estado == "Veracruz" & año_publicacion == 2006 ~ 1,
                                    estado == "Veracruz" & año_publicacion == 2008 ~ 1,
                                    estado == "Veracruz" & año_publicacion == 2012 ~ 1,
                                    estado == "Veracruz" & año_publicacion == 2015 ~ 2,
                                    estado == "Yucatán" & año_publicacion == 2003 ~ 1,
                                    estado == "Yucatán" & año_publicacion == 2006 ~ 3,
                                    estado == "Yucatán" & año_publicacion == 2012 ~ 0,
                                    estado == "Yucatán" & año_publicacion == 2014 ~ 2,
                                    estado == "Zacatecas" & año_publicacion == 2003 ~ 1,
                                    estado == "Zacatecas" & año_publicacion == 2006 ~ 1,
                                    estado == "Zacatecas" & año_publicacion == 2009 ~ 1,
                                    estado == "Zacatecas" & año_publicacion == 2012 ~ 1,
                                    estado == "Zacatecas" & año_publicacion == 2015 ~ 2))


### Repetir observación correspondiente a una norma tantas veces como elecciones haya estado vigente ----

# Dado que en algunos casos num_elecciones es igual a 0 (ver comentarios anteriores para entender por qué esto puede ocurrir), estas observaciones serán eliminadas de la base de datos. 

bd_indice_edos <- 
  bd_indice_edos %>% 
  # Repetir observaciones tantas veces como el valor de num_elecciones para el renglón correspondiente
  uncount(weights = num_elecciones) %>%
  # Generar id para identificar el número de elección en que estuvo o ha estado vigente cada norma
  group_by(estado, principio_de_representacion, año_publicacion) %>%
  mutate(id_eleccion = row_number()) %>%
  ungroup() 


### Construcción de la variable año_eleccion ----

# Esta variable indica en qué elecciones estuvo vigente cada norma en cada estado

bd_indice_edos <- 
  bd_indice_edos %>% 
  mutate(año_eleccion = case_when(estado == "Aguascalientes" & año_publicacion == 2003 & id_eleccion == 1 ~ 2004,
                                  estado == "Aguascalientes" & año_publicacion == 2003 & id_eleccion == 2 ~ 2007,
                                  estado == "Aguascalientes" & año_publicacion == 2009 & id_eleccion == 1 ~ 2010,
                                  estado == "Aguascalientes" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Aguascalientes" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Aguascalientes" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Baja California" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Baja California" & año_publicacion == 2008 & id_eleccion == 2 ~ 2013,
                                  estado == "Baja California" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Baja California" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Baja California Sur" & año_publicacion == 2003 & id_eleccion == 1 ~ 2005,
                                  estado == "Baja California Sur" & año_publicacion == 2007 & id_eleccion == 1 ~ 2008,
                                  estado == "Baja California Sur" & año_publicacion == 2007 & id_eleccion == 2 ~ 2011,
                                  estado == "Baja California Sur" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Baja California Sur" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Campeche" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "Campeche" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Campeche" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Campeche" & año_publicacion == 2011 & id_eleccion == 1 ~ 2012,
                                  estado == "Campeche" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Campeche" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Chiapas" & año_publicacion == 2005 & id_eleccion == 1 ~ 2007,
                                  estado == "Chiapas" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Chiapas" & año_publicacion == 2011 & id_eleccion == 1 ~ 2013,
                                  estado == "Chiapas" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Chiapas" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Chihuahua" & año_publicacion == 1997 & id_eleccion == 1 ~ 1998,
                                  estado == "Chihuahua" & año_publicacion == 1997 & id_eleccion == 2 ~ 2001,
                                  estado == "Chihuahua" & año_publicacion == 1997 & id_eleccion == 3 ~ 2004,
                                  estado == "Chihuahua" & año_publicacion == 1997 & id_eleccion == 4 ~ 2007,
                                  estado == "Chihuahua" & año_publicacion == 2009 & id_eleccion == 1 ~ 2010,
                                  estado == "Chihuahua" & año_publicacion == 2009 & id_eleccion == 2 ~ 2013,
                                  estado == "Chihuahua" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Chihuahua" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Ciudad de México" & año_publicacion == 1999 & id_eleccion == 1 ~ 2000,
                                  estado == "Ciudad de México" & año_publicacion == 2001 & id_eleccion == 1 ~ 2003,
                                  estado == "Ciudad de México" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Ciudad de México" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Ciudad de México" & año_publicacion == 2011 & id_eleccion == 1 ~ 2012,
                                  estado == "Ciudad de México" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Ciudad de México" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Coahuila" & año_publicacion == 2001 & id_eleccion == 1 ~ 2003,
                                  estado == "Coahuila" & año_publicacion == 2001 & id_eleccion == 2 ~ 2006,
                                  estado == "Coahuila" & año_publicacion == 2001 & id_eleccion == 3 ~ 2009,
                                  estado == "Coahuila" & año_publicacion == 2010 & id_eleccion == 1 ~ 2012,
                                  estado == "Coahuila" & año_publicacion == 2010 & id_eleccion == 2 ~ 2015,
                                  estado == "Coahuila" & año_publicacion == 2016 & id_eleccion == 1 ~ 2018,
                                  estado == "Colima" & año_publicacion == 1999 & id_eleccion == 1 ~ 2000,
                                  estado == "Colima" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "Colima" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Colima" & año_publicacion == 2005 & id_eleccion == 2 ~ 2009,
                                  estado == "Colima" & año_publicacion == 2005 & id_eleccion == 3 ~ 2012,
                                  estado == "Colima" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Colima" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Durango" & año_publicacion == 2000 & id_eleccion == 1 ~ 2001,
                                  estado == "Durango" & año_publicacion == 2000 & id_eleccion == 2 ~ 2004,
                                  estado == "Durango" & año_publicacion == 2000 & id_eleccion == 3 ~ 2007,
                                  estado == "Durango" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Durango" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Durango" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Durango" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Estado de México" & año_publicacion == 1999 & id_eleccion == 1 ~ 2000,
                                  estado == "Estado de México" & año_publicacion == 1999 & id_eleccion == 2 ~ 2003,
                                  estado == "Estado de México" & año_publicacion == 1999 & id_eleccion == 3 ~ 2006,
                                  estado == "Estado de México" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Estado de México" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "Estado de México" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Estado de México" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Guanajuato" & año_publicacion == 1994 & id_eleccion == 1 ~ 1997,
                                  estado == "Guanajuato" & año_publicacion == 1994 & id_eleccion == 2 ~ 2000,
                                  estado == "Guanajuato" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "Guanajuato" & año_publicacion == 2002 & id_eleccion == 2 ~ 2006,
                                  estado == "Guanajuato" & año_publicacion == 2002 & id_eleccion == 3 ~ 2009,
                                  estado == "Guanajuato" & año_publicacion == 2002 & id_eleccion == 4 ~ 2012,
                                  estado == "Guanajuato" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Guanajuato" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Guerrero" & año_publicacion == 1998 & id_eleccion == 1 ~ 1999,
                                  estado == "Guerrero" & año_publicacion == 1998 & id_eleccion == 2 ~ 2002,
                                  estado == "Guerrero" & año_publicacion == 2004 & id_eleccion == 1 ~ 2005,
                                  estado == "Guerrero" & año_publicacion == 2004 & id_eleccion == 2 ~ 2008,
                                  estado == "Guerrero" & año_publicacion == 2008 & id_eleccion == 1 ~ 2012,
                                  estado == "Guerrero" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Guerrero" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Hidalgo" & año_publicacion == 2007 & id_eleccion == 1 ~ 2008,
                                  estado == "Hidalgo" & año_publicacion == 2009 & id_eleccion == 1 ~ 2010,
                                  estado == "Hidalgo" & año_publicacion == 2009 & id_eleccion == 2 ~ 2013,
                                  estado == "Hidalgo" & año_publicacion == 2014 & id_eleccion == 1 ~ 2016,
                                  estado == "Hidalgo" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Jalisco" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "Jalisco" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Jalisco" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Jalisco" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "Jalisco" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Jalisco" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Michoacán" & año_publicacion == 2001 & id_eleccion == 1 ~ 2004,
                                  estado == "Michoacán" & año_publicacion == 2007 & id_eleccion == 1 ~ 2008,
                                  estado == "Michoacán" & año_publicacion == 2007 & id_eleccion == 2 ~ 2011,
                                  estado == "Michoacán" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Michoacán" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Morelos" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Morelos" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "Morelos" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Morelos" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Nayarit" & año_publicacion == 2013 & id_eleccion == 1 ~ 2015,
                                  estado == "Nayarit" & año_publicacion == 2013 & id_eleccion == 2 ~ 2017,
                                  estado == "Nuevo León" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Nuevo León" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "Nuevo León" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Nuevo León" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Oaxaca" & año_publicacion == 1997 & id_eleccion == 1 ~ 2001,
                                  estado == "Oaxaca" & año_publicacion == 1997 & id_eleccion == 2 ~ 2004,
                                  estado == "Oaxaca" & año_publicacion == 1997 & id_eleccion == 3 ~ 2007,
                                  estado == "Oaxaca" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Oaxaca" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Oaxaca" & año_publicacion == 2012 & id_eleccion == 2 ~ 2016,
                                  estado == "Oaxaca" & año_publicacion == 2012 & id_eleccion == 3 ~ 2018,
                                  estado == "Puebla" & año_publicacion == 2000 & id_eleccion == 1 ~ 2001,
                                  estado == "Puebla" & año_publicacion == 2000 & id_eleccion == 2 ~ 2004,
                                  estado == "Puebla" & año_publicacion == 2000 & id_eleccion == 3 ~ 2007,
                                  estado == "Puebla" & año_publicacion == 2000 & id_eleccion == 4 ~ 2010,
                                  estado == "Puebla" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Puebla" & año_publicacion == 2013 & id_eleccion == 1 ~ 2014,
                                  estado == "Puebla" & año_publicacion == 2016 & id_eleccion == 1 ~ 2018,
                                  estado == "Querétaro" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "Querétaro" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Querétaro" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "Querétaro" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "Querétaro" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Querétaro" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Quintana Roo" & año_publicacion == 2004 & id_eleccion == 1 ~ 2005,
                                  estado == "Quintana Roo" & año_publicacion == 2007 & id_eleccion == 1 ~ 2008,
                                  estado == "Quintana Roo" & año_publicacion == 2010 & id_eleccion == 1 ~ 2011,
                                  estado == "Quintana Roo" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Quintana Roo" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Quintana Roo" & año_publicacion == 2015 & id_eleccion == 2 ~ 2019,
                                  estado == "San Luis Potosí" & año_publicacion == 1999 & id_eleccion == 1 ~ 2000,
                                  estado == "San Luis Potosí" & año_publicacion == 2002 & id_eleccion == 1 ~ 2003,
                                  estado == "San Luis Potosí" & año_publicacion == 2002 & id_eleccion == 2 ~ 2006,
                                  estado == "San Luis Potosí" & año_publicacion == 2008 & id_eleccion == 1 ~ 2009,
                                  estado == "San Luis Potosí" & año_publicacion == 2008 & id_eleccion == 2 ~ 2012,
                                  estado == "San Luis Potosí" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "San Luis Potosí" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Sinaloa" & año_publicacion == 1998 & id_eleccion == 1 ~ 2001,
                                  estado == "Sinaloa" & año_publicacion == 1998 & id_eleccion == 2 ~ 2004,
                                  estado == "Sinaloa" & año_publicacion == 2006 & id_eleccion == 1 ~ 2007,
                                  estado == "Sinaloa" & año_publicacion == 2006 & id_eleccion == 2 ~ 2010,
                                  estado == "Sinaloa" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Sinaloa" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Sinaloa" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Sonora" & año_publicacion == 1996 & id_eleccion == 1 ~ 1997,
                                  estado == "Sonora" & año_publicacion == 1996 & id_eleccion == 2 ~ 2000,
                                  estado == "Sonora" & año_publicacion == 1996 & id_eleccion == 3 ~ 2003,
                                  estado == "Sonora" & año_publicacion == 2005 & id_eleccion == 1 ~ 2006,
                                  estado == "Sonora" & año_publicacion == 2005 & id_eleccion == 2 ~ 2009,
                                  estado == "Sonora" & año_publicacion == 2005 & id_eleccion == 3 ~ 2012,
                                  estado == "Sonora" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Sonora" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Tabasco" & año_publicacion == 2002 & id_eleccion == 1 ~ 2004,
                                  estado == "Tabasco" & año_publicacion == 2002 & id_eleccion == 2 ~ 2007,
                                  estado == "Tabasco" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Tabasco" & año_publicacion == 2011 & id_eleccion == 1 ~ 2013,
                                  estado == "Tabasco" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Tabasco" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Tamaulipas" & año_publicacion == 2003 & id_eleccion == 1 ~ 2005,
                                  estado == "Tamaulipas" & año_publicacion == 2006 & id_eleccion == 1 ~ 2008,
                                  estado == "Tamaulipas" & año_publicacion == 2008 & id_eleccion == 1 ~ 2011,
                                  estado == "Tamaulipas" & año_publicacion == 2008 & id_eleccion == 2 ~ 2013,
                                  estado == "Tamaulipas" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Tlaxcala" & año_publicacion == 2004 & id_eleccion == 1 ~ 2007,
                                  estado == "Tlaxcala" & año_publicacion == 2004 & id_eleccion == 2 ~ 2010,
                                  estado == "Tlaxcala" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Tlaxcala" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Tlaxcala" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Veracruz" & año_publicacion == 2006 & id_eleccion == 1 ~ 2007,
                                  estado == "Veracruz" & año_publicacion == 2008 & id_eleccion == 1 ~ 2010,
                                  estado == "Veracruz" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Veracruz" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Veracruz" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018,
                                  estado == "Yucatán" & año_publicacion == 2003 & id_eleccion == 1 ~ 2004,
                                  estado == "Yucatán" & año_publicacion == 2006 & id_eleccion == 1 ~ 2007,
                                  estado == "Yucatán" & año_publicacion == 2006 & id_eleccion == 2 ~ 2010,
                                  estado == "Yucatán" & año_publicacion == 2006 & id_eleccion == 3 ~ 2012,
                                  estado == "Yucatán" & año_publicacion == 2014 & id_eleccion == 1 ~ 2015,
                                  estado == "Yucatán" & año_publicacion == 2014 & id_eleccion == 2 ~ 2018,
                                  estado == "Zacatecas" & año_publicacion == 2003 & id_eleccion == 1 ~ 2004,
                                  estado == "Zacatecas" & año_publicacion == 2006 & id_eleccion == 1 ~ 2007,
                                  estado == "Zacatecas" & año_publicacion == 2009 & id_eleccion == 1 ~ 2010,
                                  estado == "Zacatecas" & año_publicacion == 2012 & id_eleccion == 1 ~ 2013,
                                  estado == "Zacatecas" & año_publicacion == 2015 & id_eleccion == 1 ~ 2016,
                                  estado == "Zacatecas" & año_publicacion == 2015 & id_eleccion == 2 ~ 2018)) %>% 
  select(estado:año_publicacion, año_eleccion, everything())




